# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyReactNativeApp' do
  pod 'AppCenter/Crashes', '~> 1.9.0'
  pod 'AppCenter/Analytics', '~> 1.9.0'
  pod 'AppCenterReactNativeShared', '~> 1.8.1'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MyReactNativeApp

  

  platform :ios, '9.0'
  target 'MyReactNativeAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'MyReactNativeApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MyReactNativeApp-tvOS

  target 'MyReactNativeApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
